import {
  IndexedBlock,
  IndexedTx,
  IndexedValidator,
  NetworkStats,
  SmartContract,
  EcosystemProject,
  MarketAsset,
  SIPItem,
  GovernanceProposal,
  ResearchPaper,
} from "@/types";

export const MOCK_GENESIS_VALIDATORS: IndexedValidator[] = [
  {
    operator_address: "spraxvaloper1q8x9y7w6e5r4t3y2u1i0o9p8a7s6d5f4g3h2j1",
    moniker: "SPRX Core Genesis Alpha",
    voting_power: 3500000,
    voting_power_percentage: 35.0,
    tokens: "3,500,000 SPRX",
    commission_rate: 0.05,
    status: "Active",
    is_tombstoned: false,
    missed_blocks_count: 0,
    uptime_percentage: 99.98,
    blocks_proposed_count: 48920,
  },
  {
    operator_address: "spraxvaloper1a2s3d4f5g6h7j8k9l0z1x2c3v4b5n6m7q8w9e0",
    moniker: "Global Real-World X Node",
    voting_power: 2800000,
    voting_power_percentage: 28.0,
    tokens: "2,800,000 SPRX",
    commission_rate: 0.04,
    status: "Active",
    is_tombstoned: false,
    missed_blocks_count: 1,
    uptime_percentage: 99.95,
    blocks_proposed_count: 39150,
  },
  {
    operator_address: "spraxvaloper1z9y8x7w6v5u4t3s2r1q0p9o8n7m6l5k4j3h2g1",
    moniker: "Nexus Staking Labs",
    voting_power: 1900000,
    voting_power_percentage: 19.0,
    tokens: "1,900,000 SPRX",
    commission_rate: 0.05,
    status: "Active",
    is_tombstoned: false,
    missed_blocks_count: 3,
    uptime_percentage: 99.89,
    blocks_proposed_count: 26400,
  },
  {
    operator_address: "spraxvaloper1m0n9b8v7c6x5z4l3k2j1h0g9f8d7s6a5q4w3e2",
    moniker: "Hyperion Validator",
    voting_power: 1200000,
    voting_power_percentage: 12.0,
    tokens: "1,200,000 SPRX",
    commission_rate: 0.08,
    status: "Active",
    is_tombstoned: false,
    missed_blocks_count: 6,
    uptime_percentage: 99.72,
    blocks_proposed_count: 16800,
  },
  {
    operator_address: "spraxvaloper1p1o2i3u4y5t6r7e8w9q0a1s2d3f4g5h6j7k8l9",
    moniker: "Antares Infrastructure",
    voting_power: 600000,
    voting_power_percentage: 6.0,
    tokens: "600,000 SPRX",
    commission_rate: 0.10,
    status: "Active",
    is_tombstoned: false,
    missed_blocks_count: 12,
    uptime_percentage: 99.45,
    blocks_proposed_count: 8400,
  },
];

export const MOCK_GENESIS_BLOCKS: IndexedBlock[] = Array.from({ length: 20 }, (_, i) => {
  const height = 8245920 - i;
  const now = Math.floor(Date.now() / 1000) - i * 2;
  const proposer = MOCK_GENESIS_VALIDATORS[i % MOCK_GENESIS_VALIDATORS.length].operator_address;
  return {
    height,
    hash: `0x7f8a9b2c3d4e5f60718293a4b5c6d7e8f901a2b3c4d5e6f708192a3b4c5d6e7${i % 10}`,
    parent_hash: `0x6e7d8c9b0a1f2e3d4c5b6a708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b${(i + 1) % 10}`,
    chain_id: "sprax-mainnet-1",
    timestamp_unix_secs: now,
    proposer,
    txs_count: (i * 7 + 3) % 18 + 1,
    txs_root: "0x11223344556677889900aabbccddeeff00112233445566778899aabbccddeeff",
    state_root: "0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
    gas_used: 145000 + (i * 12500),
    block_size_bytes: 4200 + (i * 350),
  };
});

export const MOCK_GENESIS_TXS: IndexedTx[] = Array.from({ length: 30 }, (_, i) => {
  const height = 8245920 - Math.floor(i / 2);
  const now = Math.floor(Date.now() / 1000) - i * 3;
  const types = ["Transfer", "Delegate", "ContractCall", "Transfer", "Undelegate", "Transfer"];
  const msgType = types[i % types.length];
  const senders = [
    "sprax1sdtpz05x2r7d70u428v2ff3rtyj49z65a380gr",
    "sprax1q8x9y7w6e5r4t3y2u1i0o9p8a7s6d5f4g3h2j1",
    "sprax1a2s3d4f5g6h7j8k9l0z1x2c3v4b5n6m7q8w9e0",
  ];
  const recipients = [
    "sprax1z9y8x7w6v5u4t3s2r1q0p9o8n7m6l5k4j3h2g1",
    "sprax1m0n9b8v7c6x5z4l3k2j1h0g9f8d7s6a5q4w3e2",
    "sprax14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9syh7p89",
  ];

  return {
    tx_hash: `0x89abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234567${i.toString(16).padStart(2, "0")}`,
    block_height: height,
    block_hash: `0x7f8a9b2c3d4e5f60718293a4b5c6d7e8f901a2b3c4d5e6f708192a3b4c5d6e7${(i % 10)}`,
    sender: senders[i % senders.length],
    recipient: msgType === "Transfer" ? recipients[i % recipients.length] : null,
    message_type: msgType,
    amount: `${((i + 1) * 24.5).toFixed(2)} SPRX`,
    fee_amount: "0.0005 SPRX",
    nonce: i + 1,
    memo: i % 3 === 0 ? "SPRX Settlement" : "",
    success: i !== 7,
    gas_used: msgType === "ContractCall" ? 85000 : 21000,
    timestamp_unix_secs: now,
  };
});

export const MOCK_GENESIS_STATS: NetworkStats = {
  chain_id: "sprax-mainnet-1",
  latest_height: 8245920,
  latest_block_hash: "0x7f8a9b2c3d4e5f60718293a4b5c6d7e8f901a2b3c4d5e6f708192a3b4c5d6e70",
  total_transactions: 14852910,
  total_accounts: 342180,
  active_validators_count: 100,
  total_bonded_tokens: "420,000,000 SPRX",
  avg_block_time_seconds: 1.5,
  current_tps: 1240.5,
  latest_state_root: "0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
};

export const MOCK_GENESIS_CONTRACTS: SmartContract[] = [
  {
    address: "sprax14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9syh7p89",
    creator: "sprax1sdtpz05x2r7d70u428v2ff3rtyj49z65a380gr",
    created_height: 124000,
    bytecode_size: 48200,
    tx_count: 894000,
    verified: true,
    compiler_version: "cosmwasm-rust:1.80.0",
    abi: JSON.stringify({ contract: "CW20-RealWorldUSD", standard: "SXS-20", decimals: 6, symbol: "sUSD" }, null, 2),
    source_code: `// CW20 Standard Token Implementation for RealWorld USD on SPRX
use cosmwasm_std::{entry_point, Binary, Deps, DepsMut, Env, MessageInfo, Response, StdResult};
use cw20_base::contract::{execute as cw20_execute, instantiate as cw20_instantiate, query as cw20_query};
use cw20_base::msg::{ExecuteMsg, InstantiateMsg, QueryMsg};

#[entry_point]
pub fn instantiate(deps: DepsMut, env: Env, info: MessageInfo, msg: InstantiateMsg) -> StdResult<Response> {
    cw20_instantiate(deps, env, info, msg)
}

#[entry_point]
pub fn execute(deps: DepsMut, env: Env, info: MessageInfo, msg: ExecuteMsg) -> StdResult<Response> {
    cw20_execute(deps, env, info, msg)
}`,
  },
  {
    address: "sprax1v8x7y6w5e4r3t2y1u0i9o8p7a6s5d4f3g2h1j0k9l8z7x6c5v4b3n2m1q0",
    creator: "sprax1sdtpz05x2r7d70u428v2ff3rtyj49z65a380gr",
    created_height: 245000,
    bytecode_size: 64100,
    tx_count: 412000,
    verified: true,
    compiler_version: "cosmwasm-rust:1.80.0",
    abi: JSON.stringify({ contract: "MultiPartyEscrowRWA", standard: "SXS-Escrow" }, null, 2),
  },
  {
    address: "sprax1k9l8z7x6c5v4b3n2m1q0w9e8r7t6y5u4i3o2p1a0s9d8f7g6h5j4k3l2z1",
    creator: "sprax1sdtpz05x2r7d70u428v2ff3rtyj49z65a380gr",
    created_height: 520000,
    bytecode_size: 38900,
    tx_count: 154000,
    verified: true,
    compiler_version: "cosmwasm-rust:1.80.0",
    abi: JSON.stringify({ contract: "OnChainGovernanceTreasury", standard: "SXS-Gov" }, null, 2),
  },
];

export const MOCK_ECOSYSTEM_PROJECTS: EcosystemProject[] = [
  {
    id: "sprax-swap",
    name: "SpraxSwap DEX",
    tagline: "Ultra-low latency AMM and Orderbook Hybrid",
    description: "Next-generation decentralized exchange with concentrated liquidity, sub-second settlement, and native multi-asset fee routing.",
    category: "DeFi",
    stage: "Mainnet",
    verified: true,
    website: "https://swap.sprax.network",
    github: "https://github.com/sprax-chain/sprax-swap",
    metrics: { label: "24h Volume", value: "$4.2M" },
  },
  {
    id: "sprax-rwa-settlement",
    name: "SPRX Settlement Rails",
    tagline: "Institutional Real-World Asset Tokenization & Settlement",
    description: "Compliant digital bond, real estate, and invoice tokenization infrastructure with automated dividend distribution and legal escrow anchors.",
    category: "RWA & Payments",
    stage: "Mainnet",
    verified: true,
    website: "https://rwa.sprax.network",
    metrics: { label: "Total Asset Value", value: "$18.5M" },
  },
  {
    id: "sprax-wallet-mobile",
    name: "SPRX Mobile & Web Wallet",
    tagline: "Non-custodial, multi-currency HD wallet suite",
    description: "Hardware-grade key security, BIP-39 mnemonic recovery, biometric signing, fiat conversions, and seamless dApp connect.",
    category: "Wallets",
    stage: "Mainnet",
    verified: true,
    website: "https://wallet.sprax.network",
    github: "https://github.com/sprax-chain/sprax/tree/main/apps/mobile-wallet",
    metrics: { label: "Active Users", value: "85K+" },
  },
  {
    id: "sprax-perp",
    name: "SpraxPerp Perpetual Futures",
    tagline: "Zero-slippage synthetic perps with on-chain oracles",
    description: "High-frequency decentralized perpetual contracts powered by real-time oracle price aggregation and sub-second CometBFT finality.",
    category: "DeFi",
    stage: "Mainnet",
    verified: true,
    website: "https://perps.sprax.network",
    metrics: { label: "Open Interest", value: "$8.9M" },
  },
  {
    id: "sprax-depin-node",
    name: "SPRX DePIN Sensor Mesh",
    tagline: "Verifiable IoT and energy telemetry on-chain",
    description: "Lightweight cryptographic attestation nodes for decentralized physical infrastructure networks and real-world sensor streams.",
    category: "Enterprise",
    stage: "Testnet",
    verified: true,
    website: "https://depin.sprax.network",
    metrics: { label: "Active Nodes", value: "1,420" },
  },
  {
    id: "sprax-id-credentials",
    name: "SPRX Identity & SXS-Credentials",
    tagline: "Sovereign verifiable credentials and KYC abstractions",
    description: "Privacy-preserving zero-knowledge identity assertions for compliant institutional DeFi and enterprise access control.",
    category: "Gaming & Identity",
    stage: "In Development",
    verified: true,
    website: "https://id.sprax.network",
    metrics: { label: "Credentials Issued", value: "32K" },
  },
  {
    id: "sprax-indexer-api",
    name: "SPRX Graph Indexer",
    tagline: "Real-time GraphQL and REST indexing layer",
    description: "High-throughput block indexing engine providing sub-10ms query response times for enterprise dApps and analytics dashboards.",
    category: "Infrastructure",
    stage: "Mainnet",
    verified: true,
    website: "https://indexer.sprax.network",
    github: "https://github.com/sprax-chain/sprax/tree/main/crates/sprax-indexer",
    metrics: { label: "Avg Query Latency", value: "8ms" },
  },
];

export const MOCK_MARKET_ASSETS: MarketAsset[] = [
  {
    id: "sprx",
    symbol: "SPRX",
    name: "SPRX Native",
    priceUsd: 1.48,
    change24h: 6.84,
    high24h: 1.54,
    low24h: 1.36,
    volume24hUsd: 8450200,
    marketCapUsd: 1480000000,
    circulatingSupply: "1,000,000,000 SPRX",
    sparkline: [1.36, 1.38, 1.41, 1.39, 1.44, 1.46, 1.48],
    category: "Native",
  },
  {
    id: "susd",
    symbol: "sUSD",
    name: "SPRX Real-World USD",
    priceUsd: 1.00,
    change24h: 0.02,
    high24h: 1.002,
    low24h: 0.998,
    volume24hUsd: 12400000,
    marketCapUsd: 45000000,
    circulatingSupply: "45,000,000 sUSD",
    sparkline: [1.00, 1.00, 1.001, 0.999, 1.00, 1.00, 1.00],
    category: "Stable Asset",
  },
  {
    id: "sprax-swap-token",
    name: "SpraxSwap Governance",
    symbol: "SSWAP",
    priceUsd: 0.62,
    change24h: 4.15,
    high24h: 0.65,
    low24h: 0.58,
    volume24hUsd: 1820000,
    marketCapUsd: 18600000,
    circulatingSupply: "30,000,000 SSWAP",
    sparkline: [0.58, 0.59, 0.60, 0.61, 0.60, 0.63, 0.62],
    category: "DeFi",
  },
  {
    id: "sprax-rwa-bond",
    name: "SPRX Treasury Yield Bond",
    symbol: "sTBOND",
    priceUsd: 104.20,
    change24h: 0.12,
    high24h: 104.25,
    low24h: 104.10,
    volume24hUsd: 3100000,
    marketCapUsd: 25000000,
    circulatingSupply: "240,000 sTBOND",
    sparkline: [104.10, 104.12, 104.15, 104.18, 104.19, 104.20, 104.20],
    category: "RWA",
  },
];

export const MOCK_SIPS: SIPItem[] = [
  {
    id: 1,
    sipNumber: "SIP-001",
    title: "CometBFT Consensus & Dynamic Weighted Round-Robin Proposer Selection",
    author: "SPRX Core Engineering Guild",
    status: "Final",
    category: "Consensus",
    createdDate: "2026-01-15",
    summary: "Formalizes Byzantine Fault Tolerant state-machine replication with deterministic round-robin proposer election prioritizing validator voting power and 1.5s block finality.",
    motivation: "Guarantees mathematical safety under 1/3 Byzantine adversarial thresholds and eliminates selfish proposing attacks.",
    specification: "Proposer priority increases by validator voting power at each step. The highest priority validator proposes block H.",
    rationale: "Battle-tested across Cosmos and CometBFT ecosystems, ensuring deterministic low-latency settlement.",
  },
  {
    id: 2,
    sipNumber: "SIP-002",
    title: "CosmWasm Actor-Model WASM Virtual Machine (sprax-wasm)",
    author: "SPRX Virtual Machine Working Group",
    status: "Final",
    category: "Execution",
    createdDate: "2026-02-10",
    summary: "Defines deterministic WebAssembly execution runtime with strict step-wise gas metering, memory boundaries, and non-reentrancy call stack guards.",
    motivation: "Enables secure, high-performance Rust smart contracts without the vulnerabilities inherent in EVM reentrancy and unchecked overflow.",
    specification: "Contracts export instantiate, execute, and query handlers. Sandboxed KV state isolation prevents cross-contract tampering.",
    rationale: "Rust compile-time safety and WASM isolation ensure enterprise-grade stability for complex financial logic.",
  },
  {
    id: 3,
    sipNumber: "SIP-003",
    title: "Decoupled Universal Multi-Currency Presentation Layer",
    author: "SPRX UX Architecture Team",
    status: "Final",
    category: "Standards",
    createdDate: "2026-03-05",
    summary: "Standardizes decentralized oracle price feed consumption in wallets and explorers to display balances in USD, INR, EUR, GBP, and JPY without contaminating chain state.",
    motivation: "Bridges blockchain precision with tangible real-world accounting for global users.",
    specification: "All consensus operations compute in 18-decimal atto-SPRX. Presentation layers query authenticated off-chain feeds.",
    rationale: "Keeps consensus strictly deterministic and free from off-chain oracle dependency inside the execution block cycle.",
  },
  {
    id: 4,
    sipNumber: "SIP-004",
    title: "SXS-20 & SXS-721 Real-World Extensible Asset Standards",
    author: "SPRX Standards Committee",
    status: "Review",
    category: "Standards",
    createdDate: "2026-05-20",
    summary: "Extensible smart contract specifications for fungible tokens, real-world asset collateral, and multi-signature regulatory escrow.",
    motivation: "Provides standard interfaces for institutional token issuance, automated dividend payouts, and KYC assertion checks.",
    specification: "Standard message interfaces for Transfer, Approve, MintWithMetadata, and EscrowDeposit.",
    rationale: "Unifies dApp interoperability across DeFi and real-world asset settlement platforms.",
  },
  {
    id: 5,
    sipNumber: "SIP-005",
    title: "Dual-Tier Storage Architecture: Jellyfish Merkle Trie & Redb Block Log",
    author: "SPRX Core Storage Team",
    status: "Accepted",
    category: "Core",
    createdDate: "2026-06-12",
    summary: "Implements memory-efficient pure-Rust state persistence using Redb and sparse Merkle state roots for instantaneous snapshot sync.",
    motivation: "Eliminates heavy C++ database dependencies while guaranteeing crash consistency and sub-millisecond state reads.",
    specification: "Separates state KV store from append-only raw block logs with automated WAL checkpointing.",
    rationale: "Reduces validator memory footprint by 45% compared to legacy storage models.",
  },
];

export const MOCK_GOVERNANCE_PROPOSALS: GovernanceProposal[] = [
  {
    id: 12,
    title: "Parameter Update: Reduce Minimum Validator Self-Stake to 500 SPRX",
    description: "Proposal to adjust network staking parameters to encourage broader validator decentralization across global regional nodes.",
    proposer: "sprax1sdtpz05x2r7d70u428v2ff3rtyj49z65a380gr",
    status: "Voting",
    category: "ParameterChange",
    totalDeposit: "1,000 SPRX",
    minDepositRequired: "1,000 SPRX",
    votingEndTime: "2026-08-28 18:00 UTC",
    votes: {
      yes: 78.4,
      no: 12.1,
      noWithVeto: 1.5,
      abstain: 8.0,
    },
    quorumMet: true,
    timelockDelayHours: 48,
  },
  {
    id: 11,
    title: "Ecosystem Grant: Funding for Open-Source Python & Go SPRX Client SDKs",
    description: "Disburse 50,000 SPRX from Community Pool to developer collective for building production-grade Python and Go client SDKs.",
    proposer: "sprax1q8x9y7w6e5r4t3y2u1i0o9p8a7s6d5f4g3h2j1",
    status: "Passed",
    category: "CommunityPoolSpend",
    totalDeposit: "1,000 SPRX",
    minDepositRequired: "1,000 SPRX",
    votingEndTime: "2026-08-14 12:00 UTC",
    votes: {
      yes: 94.2,
      no: 3.1,
      noWithVeto: 0.2,
      abstain: 2.5,
    },
    quorumMet: true,
    timelockDelayHours: 24,
  },
];

export const MOCK_RESEARCH_PAPERS: ResearchPaper[] = [
  {
    id: "sprx-consensus-math",
    title: "Formal Liveness & Safety Guarantees of BFT-PoS Under Partial Asynchrony",
    authors: ["SPRX Protocol Research Group", "Dr. A. Verma", "K. Thorne"],
    date: "2026-04-18",
    category: "Consensus",
    abstract: "We prove mathematical safety invariants of the SPRX CometBFT consensus engine under network partitions and Byzantine equivocation, establishing optimal 1.5s block finality with minimal message complexity.",
    readingMinutes: 14,
  },
  {
    id: "sprx-rwa-framework",
    title: "Deterministic Settlement Rails for Real-World Asset Tokenization",
    authors: ["Institutional DeFi Lab", "SPRX Legal Architecture Guild"],
    date: "2026-06-02",
    category: "RWA Legal Rails",
    abstract: "A comprehensive framework integrating cryptographic on-chain state commitments with off-chain legal custodianship, automated dividend distribution, and multi-jurisdictional compliance.",
    readingMinutes: 22,
  },
  {
    id: "sprx-storage-jmt",
    title: "Jellyfish Sparse Merkle Trees & Memory-Mapped State Persistence in Rust",
    authors: ["SPRX Storage Engineering Team"],
    date: "2026-07-20",
    category: "State Storage",
    abstract: "Analyzing the performance characteristics of sparse Merkle commitment schemes combined with memory-mapped embedded key-value stores for high-throughput Layer-1 execution engines.",
    readingMinutes: 16,
  },
];
